### ISSUE TITLE
reproducible crash

### ISSUE THREAD

**Issue by Yoghurt4C** [Draylar/everything-is-a-hat#5]
```
[03:20:26] [main/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: net.minecraft.class_1271 incompatible with net.minecraft.class_1269
	at net.minecraft.class_636.method_2919(class_636.java:340) ~[intermediary-minecraft-1.15-pre2-client.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1328) ~[intermediary-minecraft-1.15-pre2-client.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:1543) ~[intermediary-minecraft-1.15-pre2-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1390) ~[intermediary-minecraft-1.15-pre2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:916) ~[intermediary-minecraft-1.15-pre2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:576) [intermediary-minecraft-1.15-pre2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:202) [intermediary-minecraft-1.15-pre2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.2+build.174.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
how to:
-put an item on your head
-put another item in your hand
-aim at a solid block
-right click

**Comment by Yoghurt4C** [comment]
still happens in 1.0.4
